server:
  port: 8080
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver #아래의 JDBC가 mysql의존성 주입에 대한 부분, 127.0.01 ==> DB위치 , 포트번호, mysql의 데이터베이스 이름
    url: jdbc:mysql://127.0.0.1:3306/web_practice_demo?useUnicode=true&characterEncoding=utf8&autoReconnect=true&serverTimezone=Asia/Seoul&useOldAliasMetadataBehavior=true&zeroDateTimeNehavior=convertToNull
    username: ysh  #아이디
    password: ysh123   #비번
mybatis:
  type-aliases-package: com.ysh.exam.demo.vo  #value object가 있는 주소를 적는다
  
